name: Deploy Api to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_API_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}

on:
  # Runs on pushes targeting the default branch
  push:
    paths:
      - app/api/**/*.{js,jsx,ts,tsx}

  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_API_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_API_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_API_TOKEN }}
